### ISSUE TITLE
الملفات المحولة لا تعمل

### ISSUE THREAD

**Issue by Mo7mud** [AhmedOS/VTT-to-SRT-Converter#1]
السلام عليكم ورحمة الله وبركاته
جربت البرنامج وللأسف الملفات الناتجة لا تعمل
يبدو أن البرنامج يحذف فقط أول سطر من الملف والذى يحتوى على 
`WEBVTT`
ثم يقوم بتغيير الامتداد
بينما جربت تحويل نفس الملف على موقع فوجدت أنه يقوم بترقيم الترجمات

هذا الملف ناتج عن التحويل من خلال موقع

![image](https://user-images.githubusercontent.com/12565380/46104499-c5777280-c1d3-11e8-8981-90237be5391a.png)

الأرقام هذه 1 ، 2 ، 3 .... إلى أخره التى تسبق الترجمات غير موجودة فى ناتج البرنامج الخاص بك

**Comment by AhmedOS** [comment]
وعليكم السلام ورحمة الله وبركاته
الأرقام المشار إليها ليست ضرورية لصحة ملف الترجمة:
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#Cue_identifier
ممكن ترفع ملف الترجمة المراد تحويله وظهر فيه مشكلة؟

**Comment by AhmedOS** [comment]
@EgyptianM 
وعليكم السلام ورحمة الله وبركاته
تم إصلاح المشكلة في آخر إصدار من البرنامج، شكراً للتنويه.
https://github.com/AhmedOS/VTT-to-SRT-Converter/releases/latest
